Feature/header
ErazorWhite/project-tomeville pull request #15
Opened 2023-05-13 12:19 UTC by AlessioItaliano

Прописаний хедер та відповідні кнопки до нього. Однак поки в роботі shopping list та home сторінки , відповідні кнопки в хедері не активні . Свічер зміни тем працює нормально, як додавати кольри написав в групі

2023-05-13 12:30 UTC, Molksy commented on src/sass/index.scss
=)

2023-05-13 12:31 UTC, Molksy approved these changes
У мене все чудово працює)
поки що жодних помилок не вилазило

2023-05-13 13:48 UTC, ErazorWhite requested changes
тут розбіжність з макетом
![image](https://github.com/ErazorWhite/project-tomeville/assets/41112771/bc0116ad-1eb0-4874-8a74-5aa165b20065)
тут треба overflow: hidden
![image](https://github.com/ErazorWhite/project-tomeville/assets/41112771/2da003d6-767e-4be5-a724-9ff7f8f7a655)
треба робити хідеру
min-width: 320px;
width: 100%;
![image](https://github.com/ErazorWhite/project-tomeville/assets/41112771/73b7c015-cf40-43b1-9d76-c5e1ba768e8b)

2023-05-14 09:13 UTC, AlessioItaliano commented
Наче все виправив.

2023-05-14 21:06 UTC, mashanstrk approved these changes

2023-05-14 22:16 UTC, ErazorWhite approved these changes

2023-05-14 22:16 UTC, merged