loader
ErazorWhite/project-tomeville pull request #21
Opened 2023-05-14 16:11 UTC by NataliiaAndreieva

2023-05-14 17:10 UTC, AlessioItaliano approved these changes

2023-05-14 17:11 UTC, AlessioItaliano commented
Працює, гарна робота !

2023-05-14 23:35 UTC, ErazorWhite requested changes
Не вижу результатов работы лоадера.
Пожалуйста, стяни актуальный мейн, смерджи его изменения в свою ветку.
Затем сделай так, чтобы пока на странице Home грузятся карточки (т.е. ждём ответа от сервера) показывался лоадер поверх бэкдропа.

2023-05-15 11:53 UTC, ErazorWhite approved these changes
Супер гарно

2023-05-15 11:53 UTC, merged