add fonts in index
ErazorWhite/project-tomeville pull request #3
Opened 2023-05-11 07:05 UTC by Valerii69

2023-05-11 11:23 UTC, ErazorWhite requested changes
Будь ласка додай використання цих шрифтів у селекторі body, що знаходиться у _shared.scss
![image](https://github.com/ErazorWhite/project-tomeville/assets/41112771/b4c075b0-c342-42d3-9d8f-c4739fe61499)

2023-05-13 12:11 UTC, Molksy requested changes

2023-05-13 12:11 UTC, Molksy commented on src/images/images_funds/MedecSansFront.png
всі ці PNG вже є у папці "./images/support"
там у розмірах 1х та 2х

на моєму екрані дуже погано виглядають png - 
[Bookshelf.pdf](https://github.com/ErazorWhite/project-tomeville/files/11469619/Bookshelf.pdf)

2023-05-13 12:11 UTC, Molksy commented on src/js/benefitFunds.js
в чому саме VAR-змінні?
слайдер не працює чомусь, і на статичному слайдері всього 5 фондів, не по порядку

2023-05-13 13:32 UTC, ErazorWhite commented
Тут с Валерой обсудили.
Это ветка - черновик, аппрувить и мерджить нельзя. 

Будем разбивать изменения отсюда в две новые ветки и аккуратно добавлять через новые пул реквесты.

2023-05-13 13:32 UTC, closed without merging